language: node_js
node_js:
  - "16.6.1"
cache:
  directories:
    - node_modules
script:
  - yarn build
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
  target-branch: gh-pages
